{
 "title": "Foliage Runtimes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"foliage-runtimes\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Store Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cache_values{instance=\"$instance\"}",
     "legendFormat": "{{id}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Cache Get Keys by Value Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "cache_get_keys_by_pattern{instance=\"$instance\"}",
     "legendFormat": "{{id}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Total Go Runtime Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "fg_runtime_routines_counter{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fg_runtime_mem_alloc_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Statefun Instances",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "statefun_instances{instance=\"$instance\"}",
     "legendFormat": "{{typename}}"
    }
   ]
  },
  {
   "title": "Foliage Routines By Type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "fg_runtime_routines", "legendFormat": "{{routine_type_name}}" }
   ]
  }
 ]
}