package main

import (
	"github.com/foliagecp/easyjson"
	lg "github.com/foliagecp/sdk/statefun/logger"
	"github.com/foliagecp/sdk/statefun/system"
)

func CreateTestCMDB() {
	lg.Logln(lg.DebugLevel, ">>> Test started: CMDB creation")

	system.MsgOnErrorReturn(dbClient.CMDB.TypeCreate("datacenter"))
	system.MsgOnErrorReturn(dbClient.CMDB.TypeCreate("rack"))
	system.MsgOnErrorReturn(dbClient.CMDB.TypeCreate("server"))
	system.MsgOnErrorReturn(dbClient.CMDB.TypeCreate("storage"))
	system.MsgOnErrorReturn(dbClient.CMDB.TypeCreate("network"))
	system.MsgOnErrorReturn(dbClient.CMDB.TypeCreate("sensor"))

	dcBody1 := easyjson.NewJSONObject()
	dcBody1.SetByPath("name", easyjson.NewJSON("DC-East"))
	dcBody1.SetByPath("location", easyjson.NewJSON("New York"))
	dcBody1.SetByPath("power_capacity_kw", easyjson.NewJSON(5000))
	dcBody1.SetByPath("cooling_capacity_tons", easyjson.NewJSON(400))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("datacenter1", "datacenter", dcBody1))

	dcBody2 := easyjson.NewJSONObject()
	dcBody2.SetByPath("name", easyjson.NewJSON("DC-West"))
	dcBody2.SetByPath("location", easyjson.NewJSON("California"))
	dcBody2.SetByPath("power_capacity_kw", easyjson.NewJSON(3000))
	dcBody2.SetByPath("cooling_capacity_tons", easyjson.NewJSON(250))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("datacenter2", "datacenter", dcBody2))

	rackBody1 := easyjson.NewJSONObject()
	rackBody1.SetByPath("name", easyjson.NewJSON("Rack-A01"))
	rackBody1.SetByPath("units_total", easyjson.NewJSON(42))
	rackBody1.SetByPath("units_used", easyjson.NewJSON(28))
	rackBody1.SetByPath("power_draw_kw", easyjson.NewJSON(8.5))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("rack1", "rack", rackBody1))

	rackBody2 := easyjson.NewJSONObject()
	rackBody2.SetByPath("name", easyjson.NewJSON("Rack-A02"))
	rackBody2.SetByPath("units_total", easyjson.NewJSON(42))
	rackBody2.SetByPath("units_used", easyjson.NewJSON(35))
	rackBody2.SetByPath("power_draw_kw", easyjson.NewJSON(12.2))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("rack2", "rack", rackBody2))

	rackBody3 := easyjson.NewJSONObject()
	rackBody3.SetByPath("name", easyjson.NewJSON("Rack-B01"))
	rackBody3.SetByPath("units_total", easyjson.NewJSON(42))
	rackBody3.SetByPath("units_used", easyjson.NewJSON(18))
	rackBody3.SetByPath("power_draw_kw", easyjson.NewJSON(6.8))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("rack3", "rack", rackBody3))

	rackBody4 := easyjson.NewJSONObject()
	rackBody4.SetByPath("name", easyjson.NewJSON("Rack-B02"))
	rackBody4.SetByPath("units_total", easyjson.NewJSON(42))
	rackBody4.SetByPath("units_used", easyjson.NewJSON(22))
	rackBody4.SetByPath("power_draw_kw", easyjson.NewJSON(9.1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("rack4", "rack", rackBody4))

	serverBody1 := easyjson.NewJSONObject()
	serverBody1.SetByPath("hostname", easyjson.NewJSON("web-01"))
	serverBody1.SetByPath("cpu_cores", easyjson.NewJSON(16))
	serverBody1.SetByPath("memory_gb", easyjson.NewJSON(64))
	serverBody1.SetByPath("rack_position", easyjson.NewJSON(5))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("server1", "server", serverBody1))

	serverBody2 := easyjson.NewJSONObject()
	serverBody2.SetByPath("hostname", easyjson.NewJSON("web-02"))
	serverBody2.SetByPath("cpu_cores", easyjson.NewJSON(16))
	serverBody2.SetByPath("memory_gb", easyjson.NewJSON(64))
	serverBody2.SetByPath("rack_position", easyjson.NewJSON(7))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("server2", "server", serverBody2))

	serverBody3 := easyjson.NewJSONObject()
	serverBody3.SetByPath("hostname", easyjson.NewJSON("db-01"))
	serverBody3.SetByPath("cpu_cores", easyjson.NewJSON(32))
	serverBody3.SetByPath("memory_gb", easyjson.NewJSON(128))
	serverBody3.SetByPath("rack_position", easyjson.NewJSON(10))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("server3", "server", serverBody3))

	serverBody4 := easyjson.NewJSONObject()
	serverBody4.SetByPath("hostname", easyjson.NewJSON("db-02"))
	serverBody4.SetByPath("cpu_cores", easyjson.NewJSON(32))
	serverBody4.SetByPath("memory_gb", easyjson.NewJSON(128))
	serverBody4.SetByPath("rack_position", easyjson.NewJSON(12))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("server4", "server", serverBody4))

	serverBody5 := easyjson.NewJSONObject()
	serverBody5.SetByPath("hostname", easyjson.NewJSON("app-01"))
	serverBody5.SetByPath("cpu_cores", easyjson.NewJSON(8))
	serverBody5.SetByPath("memory_gb", easyjson.NewJSON(32))
	serverBody5.SetByPath("rack_position", easyjson.NewJSON(15))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("server5", "server", serverBody5))

	serverBody6 := easyjson.NewJSONObject()
	serverBody6.SetByPath("hostname", easyjson.NewJSON("app-02"))
	serverBody6.SetByPath("cpu_cores", easyjson.NewJSON(8))
	serverBody6.SetByPath("memory_gb", easyjson.NewJSON(32))
	serverBody6.SetByPath("rack_position", easyjson.NewJSON(8))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("server6", "server", serverBody6))

	serverBody7 := easyjson.NewJSONObject()
	serverBody7.SetByPath("hostname", easyjson.NewJSON("mon-01"))
	serverBody7.SetByPath("cpu_cores", easyjson.NewJSON(4))
	serverBody7.SetByPath("memory_gb", easyjson.NewJSON(16))
	serverBody7.SetByPath("rack_position", easyjson.NewJSON(20))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("server7", "server", serverBody7))

	serverBody8 := easyjson.NewJSONObject()
	serverBody8.SetByPath("hostname", easyjson.NewJSON("backup-01"))
	serverBody8.SetByPath("cpu_cores", easyjson.NewJSON(8))
	serverBody8.SetByPath("memory_gb", easyjson.NewJSON(32))
	serverBody8.SetByPath("rack_position", easyjson.NewJSON(25))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("server8", "server", serverBody8))

	storageBody1 := easyjson.NewJSONObject()
	storageBody1.SetByPath("name", easyjson.NewJSON("SAN-Primary"))
	storageBody1.SetByPath("type", easyjson.NewJSON("SAN"))
	storageBody1.SetByPath("capacity_tb", easyjson.NewJSON(100))
	storageBody1.SetByPath("raid_level", easyjson.NewJSON("RAID10"))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("storage1", "storage", storageBody1))

	storageBody2 := easyjson.NewJSONObject()
	storageBody2.SetByPath("name", easyjson.NewJSON("SAN-Secondary"))
	storageBody2.SetByPath("type", easyjson.NewJSON("SAN"))
	storageBody2.SetByPath("capacity_tb", easyjson.NewJSON(100))
	storageBody2.SetByPath("raid_level", easyjson.NewJSON("RAID10"))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("storage2", "storage", storageBody2))

	storageBody3 := easyjson.NewJSONObject()
	storageBody3.SetByPath("name", easyjson.NewJSON("NAS-Backup"))
	storageBody3.SetByPath("type", easyjson.NewJSON("NAS"))
	storageBody3.SetByPath("capacity_tb", easyjson.NewJSON(500))
	storageBody3.SetByPath("raid_level", easyjson.NewJSON("RAID6"))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("storage3", "storage", storageBody3))

	storageBody4 := easyjson.NewJSONObject()
	storageBody4.SetByPath("name", easyjson.NewJSON("Local-Cache"))
	storageBody4.SetByPath("type", easyjson.NewJSON("Local"))
	storageBody4.SetByPath("capacity_tb", easyjson.NewJSON(2))
	storageBody4.SetByPath("raid_level", easyjson.NewJSON("RAID1"))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("storage4", "storage", storageBody4))

	netBody1 := easyjson.NewJSONObject()
	netBody1.SetByPath("name", easyjson.NewJSON("Core-Switch-01"))
	netBody1.SetByPath("type", easyjson.NewJSON("Core"))
	netBody1.SetByPath("ports_total", easyjson.NewJSON(48))
	netBody1.SetByPath("bandwidth_gbps", easyjson.NewJSON(400))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("network1", "network", netBody1))

	netBody2 := easyjson.NewJSONObject()
	netBody2.SetByPath("name", easyjson.NewJSON("TOR-Switch-A01"))
	netBody2.SetByPath("type", easyjson.NewJSON("TOR"))
	netBody2.SetByPath("ports_total", easyjson.NewJSON(24))
	netBody2.SetByPath("bandwidth_gbps", easyjson.NewJSON(10))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("network2", "network", netBody2))

	netBody3 := easyjson.NewJSONObject()
	netBody3.SetByPath("name", easyjson.NewJSON("TOR-Switch-A02"))
	netBody3.SetByPath("type", easyjson.NewJSON("TOR"))
	netBody3.SetByPath("ports_total", easyjson.NewJSON(24))
	netBody3.SetByPath("bandwidth_gbps", easyjson.NewJSON(10))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("network3", "network", netBody3))

	netBody4 := easyjson.NewJSONObject()
	netBody4.SetByPath("name", easyjson.NewJSON("TOR-Switch-B01"))
	netBody4.SetByPath("type", easyjson.NewJSON("TOR"))
	netBody4.SetByPath("ports_total", easyjson.NewJSON(24))
	netBody4.SetByPath("bandwidth_gbps", easyjson.NewJSON(10))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("network4", "network", netBody4))

	netBody5 := easyjson.NewJSONObject()
	netBody5.SetByPath("name", easyjson.NewJSON("TOR-Switch-B02"))
	netBody5.SetByPath("type", easyjson.NewJSON("TOR"))
	netBody5.SetByPath("ports_total", easyjson.NewJSON(24))
	netBody5.SetByPath("bandwidth_gbps", easyjson.NewJSON(10))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("network5", "network", netBody5))

	sensorBody1 := easyjson.NewJSONObject()
	sensorBody1.SetByPath("type", easyjson.NewJSON("temperature"))
	sensorBody1.SetByPath("location", easyjson.NewJSON("DC-East-Inlet"))
	sensorBody1.SetByPath("value", easyjson.NewJSON(22.5))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("sensor1", "sensor", sensorBody1))

	sensorBody2 := easyjson.NewJSONObject()
	sensorBody2.SetByPath("type", easyjson.NewJSON("humidity"))
	sensorBody2.SetByPath("location", easyjson.NewJSON("DC-East-Inlet"))
	sensorBody2.SetByPath("value", easyjson.NewJSON(45.0))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("sensor2", "sensor", sensorBody2))

	sensorBody3 := easyjson.NewJSONObject()
	sensorBody3.SetByPath("type", easyjson.NewJSON("power"))
	sensorBody3.SetByPath("location", easyjson.NewJSON("Rack-A01-PDU"))
	sensorBody3.SetByPath("value", easyjson.NewJSON(8500.0))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("sensor3", "sensor", sensorBody3))

	sensorBody4 := easyjson.NewJSONObject()
	sensorBody4.SetByPath("type", easyjson.NewJSON("power"))
	sensorBody4.SetByPath("location", easyjson.NewJSON("Rack-A02-PDU"))
	sensorBody4.SetByPath("value", easyjson.NewJSON(12200.0))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("sensor4", "sensor", sensorBody4))

	sensorBody5 := easyjson.NewJSONObject()
	sensorBody5.SetByPath("type", easyjson.NewJSON("vibration"))
	sensorBody5.SetByPath("location", easyjson.NewJSON("DC-East-Floor"))
	sensorBody5.SetByPath("value", easyjson.NewJSON(0.2))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectCreate("sensor5", "sensor", sensorBody5))

	system.MsgOnErrorReturn(dbClient.CMDB.TypesLinkCreate("datacenter", "rack", "datacenter-rack", []string{"physical"}))
	system.MsgOnErrorReturn(dbClient.CMDB.TypesLinkCreate("rack", "server", "rack-server", []string{"physical"}))
	system.MsgOnErrorReturn(dbClient.CMDB.TypesLinkCreate("rack", "rack", "rack-rack", []string{"physical"}))
	system.MsgOnErrorReturn(dbClient.CMDB.TypesLinkCreate("rack", "storage", "rack-storage", []string{"physical"}))
	system.MsgOnErrorReturn(dbClient.CMDB.TypesLinkCreate("rack", "network", "rack-network", []string{"physical"}))
	system.MsgOnErrorReturn(dbClient.CMDB.TypesLinkCreate("server", "storage", "server-storage", []string{"logical"}))
	system.MsgOnErrorReturn(dbClient.CMDB.TypesLinkCreate("server", "network", "server-network", []string{"logical"}))
	system.MsgOnErrorReturn(dbClient.CMDB.TypesLinkCreate("network", "network", "network-network", []string{"logical"}))
	system.MsgOnErrorReturn(dbClient.CMDB.TypesLinkCreate("sensor", "datacenter", "sensor-datacenter", []string{"monitoring"}))
	system.MsgOnErrorReturn(dbClient.CMDB.TypesLinkCreate("sensor", "rack", "sensor-rack", []string{"monitoring"}))

	containsBody := easyjson.NewJSONObject()
	containsBody.SetByPath("zone", easyjson.NewJSON("A"))
	containsBody.SetByPath("floor", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack1", "rack1", "rack", []string{"physical"}, containsBody))

	containsBody1 := easyjson.NewJSONObject()
	containsBody1.SetByPath("zone", easyjson.NewJSON("A"))
	containsBody1.SetByPath("floor", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("datacenter1", "rack1", "dc_rack1", []string{"physical"}, containsBody1))

	containsBody2 := easyjson.NewJSONObject()
	containsBody2.SetByPath("zone", easyjson.NewJSON("A"))
	containsBody2.SetByPath("floor", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("datacenter1", "rack2", "dc_rack2", []string{"physical"}, containsBody2))

	containsBody3 := easyjson.NewJSONObject()
	containsBody3.SetByPath("zone", easyjson.NewJSON("B"))
	containsBody3.SetByPath("floor", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("datacenter2", "rack3", "dc_rack3", []string{"physical"}, containsBody3))

	containsBody4 := easyjson.NewJSONObject()
	containsBody4.SetByPath("zone", easyjson.NewJSON("B"))
	containsBody4.SetByPath("floor", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("datacenter2", "rack4", "dc_rack4", []string{"physical"}, containsBody4))

	hostsBody1 := easyjson.NewJSONObject()
	hostsBody1.SetByPath("start_unit", easyjson.NewJSON(5))
	hostsBody1.SetByPath("end_unit", easyjson.NewJSON(6))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack1", "server1", "rack_srv1", []string{"physical"}, hostsBody1))

	hostsBody2 := easyjson.NewJSONObject()
	hostsBody2.SetByPath("start_unit", easyjson.NewJSON(7))
	hostsBody2.SetByPath("end_unit", easyjson.NewJSON(8))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack1", "server2", "rack_srv2", []string{"physical"}, hostsBody2))

	hostsBody3 := easyjson.NewJSONObject()
	hostsBody3.SetByPath("start_unit", easyjson.NewJSON(10))
	hostsBody3.SetByPath("end_unit", easyjson.NewJSON(12))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack2", "server3", "rack_srv3", []string{"physical"}, hostsBody3))

	hostsBody4 := easyjson.NewJSONObject()
	hostsBody4.SetByPath("start_unit", easyjson.NewJSON(13))
	hostsBody4.SetByPath("end_unit", easyjson.NewJSON(15))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack2", "server4", "rack_srv4", []string{"physical"}, hostsBody4))

	hostsBody5 := easyjson.NewJSONObject()
	hostsBody5.SetByPath("start_unit", easyjson.NewJSON(8))
	hostsBody5.SetByPath("end_unit", easyjson.NewJSON(9))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack3", "server5", "rack_srv5", []string{"physical"}, hostsBody5))

	hostsBody6 := easyjson.NewJSONObject()
	hostsBody6.SetByPath("start_unit", easyjson.NewJSON(10))
	hostsBody6.SetByPath("end_unit", easyjson.NewJSON(11))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack3", "server6", "rack_srv6", []string{"physical"}, hostsBody6))

	hostsBody7 := easyjson.NewJSONObject()
	hostsBody7.SetByPath("start_unit", easyjson.NewJSON(15))
	hostsBody7.SetByPath("end_unit", easyjson.NewJSON(16))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack4", "server7", "rack_srv7", []string{"physical"}, hostsBody7))

	hostsBody8 := easyjson.NewJSONObject()
	hostsBody8.SetByPath("start_unit", easyjson.NewJSON(20))
	hostsBody8.SetByPath("end_unit", easyjson.NewJSON(22))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack4", "server8", "rack_srv8", []string{"physical"}, hostsBody8))

	hostsStor1 := easyjson.NewJSONObject()
	hostsStor1.SetByPath("start_unit", easyjson.NewJSON(30))
	hostsStor1.SetByPath("end_unit", easyjson.NewJSON(35))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack1", "storage1", "rack_stor1", []string{"physical"}, hostsStor1))

	hostsStor2 := easyjson.NewJSONObject()
	hostsStor2.SetByPath("start_unit", easyjson.NewJSON(30))
	hostsStor2.SetByPath("end_unit", easyjson.NewJSON(35))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack2", "storage2", "rack_stor2", []string{"physical"}, hostsStor2))

	hostsStor3 := easyjson.NewJSONObject()
	hostsStor3.SetByPath("start_unit", easyjson.NewJSON(25))
	hostsStor3.SetByPath("end_unit", easyjson.NewJSON(30))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack4", "storage3", "rack_stor3", []string{"physical"}, hostsStor3))

	hostsNet1 := easyjson.NewJSONObject()
	hostsNet1.SetByPath("start_unit", easyjson.NewJSON(1))
	hostsNet1.SetByPath("end_unit", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack1", "network2", "rack_net1", []string{"physical"}, hostsNet1))

	hostsNet2 := easyjson.NewJSONObject()
	hostsNet2.SetByPath("start_unit", easyjson.NewJSON(1))
	hostsNet2.SetByPath("end_unit", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack2", "network3", "rack_net2", []string{"physical"}, hostsNet2))

	hostsNet3 := easyjson.NewJSONObject()
	hostsNet3.SetByPath("start_unit", easyjson.NewJSON(1))
	hostsNet3.SetByPath("end_unit", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack3", "network4", "rack_net3", []string{"physical"}, hostsNet3))

	hostsNet4 := easyjson.NewJSONObject()
	hostsNet4.SetByPath("start_unit", easyjson.NewJSON(1))
	hostsNet4.SetByPath("end_unit", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("rack4", "network5", "rack_net4", []string{"physical"}, hostsNet4))

	srvConnBody1 := easyjson.NewJSONObject()
	srvConnBody1.SetByPath("interface", easyjson.NewJSON("eth0"))
	srvConnBody1.SetByPath("port", easyjson.NewJSON(5))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("server1", "network2", "srv_net1", []string{"logical"}, srvConnBody1))

	srvConnBody2 := easyjson.NewJSONObject()
	srvConnBody2.SetByPath("interface", easyjson.NewJSON("eth0"))
	srvConnBody2.SetByPath("port", easyjson.NewJSON(7))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("server2", "network2", "srv_net2", []string{"logical"}, srvConnBody2))

	srvConnBody3 := easyjson.NewJSONObject()
	srvConnBody3.SetByPath("interface", easyjson.NewJSON("eth0"))
	srvConnBody3.SetByPath("port", easyjson.NewJSON(10))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("server3", "network3", "srv_net3", []string{"logical"}, srvConnBody3))

	srvConnBody4 := easyjson.NewJSONObject()
	srvConnBody4.SetByPath("interface", easyjson.NewJSON("eth0"))
	srvConnBody4.SetByPath("port", easyjson.NewJSON(12))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("server4", "network3", "srv_net4", []string{"logical"}, srvConnBody4))

	srvStorBody1 := easyjson.NewJSONObject()
	srvStorBody1.SetByPath("protocol", easyjson.NewJSON("iSCSI"))
	srvStorBody1.SetByPath("lun", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("server1", "storage1", "srv_stor1", []string{"logical"}, srvStorBody1))

	srvStorBody2 := easyjson.NewJSONObject()
	srvStorBody2.SetByPath("protocol", easyjson.NewJSON("iSCSI"))
	srvStorBody2.SetByPath("lun", easyjson.NewJSON(2))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("server2", "storage1", "srv_stor2", []string{"logical"}, srvStorBody2))

	srvStorBody3 := easyjson.NewJSONObject()
	srvStorBody3.SetByPath("protocol", easyjson.NewJSON("iSCSI"))
	srvStorBody3.SetByPath("lun", easyjson.NewJSON(1))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("server3", "storage2", "srv_stor3", []string{"logical"}, srvStorBody3))

	srvStorBody4 := easyjson.NewJSONObject()
	srvStorBody4.SetByPath("protocol", easyjson.NewJSON("iSCSI"))
	srvStorBody4.SetByPath("lun", easyjson.NewJSON(2))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("server4", "storage2", "srv_stor4", []string{"logical"}, srvStorBody4))

	uplinkBody1 := easyjson.NewJSONObject()
	uplinkBody1.SetByPath("port_local", easyjson.NewJSON(23))
	uplinkBody1.SetByPath("port_remote", easyjson.NewJSON(1))
	uplinkBody1.SetByPath("bandwidth_gbps", easyjson.NewJSON(10))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("network2", "network1", "uplink1", []string{"logical"}, uplinkBody1))

	uplinkBody2 := easyjson.NewJSONObject()
	uplinkBody2.SetByPath("port_local", easyjson.NewJSON(23))
	uplinkBody2.SetByPath("port_remote", easyjson.NewJSON(2))
	uplinkBody2.SetByPath("bandwidth_gbps", easyjson.NewJSON(10))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("network3", "network1", "uplink2", []string{"logical"}, uplinkBody2))

	uplinkBody3 := easyjson.NewJSONObject()
	uplinkBody3.SetByPath("port_local", easyjson.NewJSON(23))
	uplinkBody3.SetByPath("port_remote", easyjson.NewJSON(3))
	uplinkBody3.SetByPath("bandwidth_gbps", easyjson.NewJSON(10))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("network4", "network1", "uplink3", []string{"logical"}, uplinkBody3))

	uplinkBody4 := easyjson.NewJSONObject()
	uplinkBody4.SetByPath("port_local", easyjson.NewJSON(23))
	uplinkBody4.SetByPath("port_remote", easyjson.NewJSON(4))
	uplinkBody4.SetByPath("bandwidth_gbps", easyjson.NewJSON(10))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("network5", "network1", "uplink4", []string{"logical"}, uplinkBody4))

	monBody1 := easyjson.NewJSONObject()
	monBody1.SetByPath("metric", easyjson.NewJSON("temperature"))
	monBody1.SetByPath("alert_threshold", easyjson.NewJSON(25.0))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("sensor1", "datacenter1", "mon1", []string{"monitoring"}, monBody1))

	monBody2 := easyjson.NewJSONObject()
	monBody2.SetByPath("metric", easyjson.NewJSON("humidity"))
	monBody2.SetByPath("alert_threshold", easyjson.NewJSON(50.0))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("sensor2", "datacenter1", "mon2", []string{"monitoring"}, monBody2))

	monBody3 := easyjson.NewJSONObject()
	monBody3.SetByPath("metric", easyjson.NewJSON("power_draw"))
	monBody3.SetByPath("alert_threshold", easyjson.NewJSON(10000.0))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("sensor3", "rack1", "mon3", []string{"monitoring"}, monBody3))

	monBody4 := easyjson.NewJSONObject()
	monBody4.SetByPath("metric", easyjson.NewJSON("power_draw"))
	monBody4.SetByPath("alert_threshold", easyjson.NewJSON(15000.0))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("sensor4", "rack2", "mon4", []string{"monitoring"}, monBody4))

	monBody5 := easyjson.NewJSONObject()
	monBody5.SetByPath("metric", easyjson.NewJSON("vibration"))
	monBody5.SetByPath("alert_threshold", easyjson.NewJSON(1.0))
	system.MsgOnErrorReturn(dbClient.CMDB.ObjectsLinkCreate("sensor5", "datacenter1", "mon5", []string{"monitoring"}, monBody5))

	lg.Logln(lg.DebugLevel, "<<< Test ended: CMDB creation")
}
