package workflow

import (
	"fmt"
	"time"

	"github.com/foliagecp/easyjson"
	"github.com/foliagecp/sdk/statefun"
	sfPlugins "github.com/foliagecp/sdk/statefun/plugins"
)

// Typename for the timer function
const DelayedSignalGeneratorTypename = "functions.system.timer.delayed_signal"

var (
	BaseSignalFunc func(signalProvider sfPlugins.SignalProvider, callerTypename string, callerID string, targetTypename string, targetID string, payload *easyjson.JSON, options *easyjson.JSON) error
)

// Public registration helper. Call this from your bootstrap code.
func RegisterDelayedSignalGenerator(runtime *statefun.Runtime) {
	BaseSignalFunc = runtime.GetBaseSignalFunc()
	statefun.NewFunctionType(runtime, DelayedSignalGeneratorTypename, DelayedSignalGeneratorHandler, *statefun.NewFunctionTypeConfig())
}

// ----- Payload schema (Signals to DelayedSignalGenerator) -----
// cmd: "schedule_once" | "schedule_every" | "cancel" | "cancel_all" | "_tick"
// config (optional): { tick_ms: number, wheel_size: number }
// task: {
//   id?: string (autogenerated if empty),
//   caller_typename: string,
//   caller_id: string,
//   target_typename: string,
//   target_id: string,
//   payload?: json,
//   options?: json,
//   // schedule_once only:
//   due_in_ms?: number,            // fire in N ms (preferred)
//   due_at_unix_ms?: number,       // absolute time
//   // schedule_every only:
//   period_ms: number,             // period in ms
//   first_in_ms?: number           // time to first fire; default = period_ms
// }

// ----- Function context layout (per id) -----
// {
//   config: { tick_ms: number, wheel_size: number },
//   current_slot: number,
//   ticker_active: bool,
//   tasks: { [task_id]: { kind: "once"|"every", caller_typename, caller_id, target_typename, target_id, payload, options, rounds: number, period_ticks: number }},
//   wheel: [ { ids: [task_id, ...] }, ... wheel_size ]
// }

// ---------- Handler ----------
func DelayedSignalGeneratorHandler(_ sfPlugins.StatefunExecutor, ctx *sfPlugins.StatefunContextProcessor) {
	cmd := ctx.Payload.GetByPath("cmd").AsStringDefault("")
	if cmd == "" {
		return
	}

	// Ensure config & wheel are initialized
	ensureWheelInitialized(ctx)

	switch cmd {
	case "schedule_once":
		scheduleOnce(ctx)
		startTickerIfNeeded(ctx)
	case "schedule_every":
		scheduleEvery(ctx)
		startTickerIfNeeded(ctx)
	case "cancel":
		cancelTask(ctx)
		stopTickerIfNoTasks(ctx)
	case "cancel_all":
		cancelAll(ctx)
		stopTickerIfNoTasks(ctx)
	case "_tick":
		processTick(ctx)
	default:
		// no-op
	}
}

// ---------- Initialization helpers ----------
func ensureWheelInitialized(ctx *sfPlugins.StatefunContextProcessor) {
	fc := ctx.GetFunctionContext()

	// Per-id configuration may be overridden via payload.config
	if ctx.Payload.PathExists("config.tick_ms") {
		fc.SetByPath("config.tick_ms", ctx.Payload.GetByPath("config.tick_ms"))
	}
	if ctx.Payload.PathExists("config.wheel_size") {
		fc.SetByPath("config.wheel_size", ctx.Payload.GetByPath("config.wheel_size"))
	}

	if !fc.PathExists("config.tick_ms") {
		fc.SetByPath("config.tick_ms", easyjson.NewJSON(1000)) // default 1s
	}
	if !fc.PathExists("config.wheel_size") {
		fc.SetByPath("config.wheel_size", easyjson.NewJSON(3600)) // default 1 hour at 1s tick
	}
	if !fc.PathExists("current_slot") {
		fc.SetByPath("current_slot", easyjson.NewJSON(0))
	}
	if !fc.PathExists("tasks") {
		fc.SetByPath("tasks", easyjson.NewJSONObject())
	}
	if !fc.PathExists("wheel") {
		wheelSize := int(fc.GetByPath("config.wheel_size").AsNumericDefault(3600))
		arr := easyjson.NewJSONArray()
		for i := 0; i < wheelSize; i++ {
			obj := easyjson.NewJSONObject()
			obj.SetByPath("ids", easyjson.NewJSONArray())
			arr.AddToArray(obj)
		}
		fc.SetByPath("wheel", arr)
	}
	ctx.SetFunctionContext(fc)
}

// ---------- Ticker state ----------
func startTickerIfNeeded(ctx *sfPlugins.StatefunContextProcessor) {
	fc := ctx.GetFunctionContext()
	if fc.GetByPath("ticker_active").AsBoolDefault(false) {
		return
	}
	if len(fc.GetByPath("tasks").ObjectKeys()) == 0 {
		return
	}
	fc.SetByPath("ticker_active", easyjson.NewJSON(true))
	ctx.SetFunctionContext(fc)
	scheduleNextTick(ctx)
}

func stopTickerIfNoTasks(ctx *sfPlugins.StatefunContextProcessor) {
	fc := ctx.GetFunctionContext()
	if len(fc.GetByPath("tasks").ObjectKeys()) == 0 {
		fc.SetByPath("ticker_active", easyjson.NewJSON(false))
		ctx.SetFunctionContext(fc)
	}
}

// ---------- Tick arming (blocking sleep + self-signal) ----------
// We intentionally block until the next tick and only then return from the handler,
// so that the NATS/JetStream message is ACKed at the very end, after the self-signal.
func scheduleNextTick(ctx *sfPlugins.StatefunContextProcessor) {
	fc := ctx.GetFunctionContext()
	tickMs := time.Duration(int64(fc.GetByPath("config.tick_ms").AsNumericDefault(1000))) * time.Millisecond
	time.Sleep(tickMs)
	payload := easyjson.NewJSONObject()
	payload.SetByPath("cmd", easyjson.NewJSON("_tick"))
	// Use JetStream signal to ensure persistence.
	_ = ctx.Signal(sfPlugins.JetstreamGlobalSignal, ctx.Self.Typename, ctx.Self.ID, &payload, nil)
}

// ---------- Scheduling API ----------
func scheduleOnce(ctx *sfPlugins.StatefunContextProcessor) {
	fc := ctx.GetFunctionContext()

	wheelSize := int(fc.GetByPath("config.wheel_size").AsNumericDefault(3600))
	tickMs := int(fc.GetByPath("config.tick_ms").AsNumericDefault(1000))

	task := ctx.Payload.GetByPath("task")
	if !task.IsObject() {
		return
	}

	taskID := task.GetByPath("id").AsStringDefault("")
	if taskID == "" {
		taskID = fmt.Sprintf("t_%d", time.Now().UnixNano())
	}

	// Compute delay in ticks
	var delayMs int64
	if task.PathExists("due_in_ms") {
		delayMs = int64(task.GetByPath("due_in_ms").AsNumericDefault(0))
	} else if task.PathExists("due_at_unix_ms") {
		now := time.Now().UnixMilli()
		delayMs = int64(task.GetByPath("due_at_unix_ms").AsNumericDefault(float64(now))) - now
		if delayMs < 0 {
			delayMs = 0
		}
	} else {
		// Default: trigger on the next tick
		delayMs = int64(tickMs)
	}

	ticksTotal := int((delayMs + int64(tickMs) - 1) / int64(tickMs)) // ceil
	if ticksTotal < 1 {
		ticksTotal = 1
	}

	currentSlot := int(fc.GetByPath("current_slot").AsNumericDefault(0))
	slot := (currentSlot + (ticksTotal % wheelSize)) % wheelSize
	rounds := ticksTotal / wheelSize

	// Persist task
	entry := easyjson.NewJSONObject()
	entry.SetByPath("kind", easyjson.NewJSON("once"))
	entry.SetByPath("caller_typename", task.GetByPath("caller_typename"))
	entry.SetByPath("caller_id", task.GetByPath("caller_id"))
	entry.SetByPath("target_typename", task.GetByPath("target_typename"))
	entry.SetByPath("target_id", task.GetByPath("target_id"))
	if task.PathExists("payload") {
		entry.SetByPath("payload", task.GetByPath("payload"))
	}
	if task.PathExists("options") {
		entry.SetByPath("options", task.GetByPath("options"))
	}
	entry.SetByPath("rounds", easyjson.NewJSON(rounds))
	fc.SetByPath("tasks."+taskID, entry)

	// Place into wheel slot: wheel.<slot>.ids += taskID
	path := fmt.Sprintf("wheel.%d.ids", slot)
	idsArr := fc.GetByPath(path)
	if !idsArr.IsArray() {
		idsArr = easyjson.NewJSONArray()
	}
	idsArr.AddToArray(easyjson.NewJSON(taskID))
	fc.SetByPath(path, idsArr)
	ctx.SetFunctionContext(fc)
}

func scheduleEvery(ctx *sfPlugins.StatefunContextProcessor) {
	fc := ctx.GetFunctionContext()
	wheelSize := int(fc.GetByPath("config.wheel_size").AsNumericDefault(3600))
	tickMs := int(fc.GetByPath("config.tick_ms").AsNumericDefault(1000))

	task := ctx.Payload.GetByPath("task")
	if !task.IsObject() {
		return
	}

	taskID := task.GetByPath("id").AsStringDefault("")
	if taskID == "" {
		taskID = fmt.Sprintf("t_%d", time.Now().UnixNano())
	}

	periodMs := int64(task.GetByPath("period_ms").AsNumericDefault(0))
	if periodMs <= 0 {
		return
	}
	periodTicks := int((periodMs + int64(tickMs) - 1) / int64(tickMs))
	if periodTicks < 1 {
		periodTicks = 1
	}

	firstMs := int64(task.GetByPath("first_in_ms").AsNumericDefault(float64(periodMs)))
	if firstMs <= 0 {
		firstMs = int64(periodMs)
	}

	ticksTotal := int((firstMs + int64(tickMs) - 1) / int64(tickMs))
	if ticksTotal < 1 {
		ticksTotal = 1
	}

	currentSlot := int(fc.GetByPath("current_slot").AsNumericDefault(0))
	slot := (currentSlot + (ticksTotal % wheelSize)) % wheelSize
	rounds := ticksTotal / wheelSize

	entry := easyjson.NewJSONObject()
	entry.SetByPath("kind", easyjson.NewJSON("every"))
	entry.SetByPath("caller_typename", task.GetByPath("caller_typename"))
	entry.SetByPath("caller_id", task.GetByPath("caller_id"))
	entry.SetByPath("target_typename", task.GetByPath("target_typename"))
	entry.SetByPath("target_id", task.GetByPath("target_id"))
	if task.PathExists("payload") {
		entry.SetByPath("payload", task.GetByPath("payload"))
	}
	if task.PathExists("options") {
		entry.SetByPath("options", task.GetByPath("options"))
	}
	entry.SetByPath("rounds", easyjson.NewJSON(rounds))
	entry.SetByPath("period_ticks", easyjson.NewJSON(periodTicks))
	fc.SetByPath("tasks."+taskID, entry)

	path := fmt.Sprintf("wheel.%d.ids", slot)
	idsArr := fc.GetByPath(path)
	if !idsArr.IsArray() {
		idsArr = easyjson.NewJSONArray()
	}
	idsArr.AddToArray(easyjson.NewJSON(taskID))
	fc.SetByPath(path, idsArr)
	ctx.SetFunctionContext(fc)
}

// ---------- Cancel API ----------
func cancelTask(ctx *sfPlugins.StatefunContextProcessor) {
	fc := ctx.GetFunctionContext()
	taskID := ctx.Payload.GetByPath("task.id").AsStringDefault("")
	if taskID == "" {
		return
	}
	if fc.PathExists("tasks." + taskID) {
		fc.RemoveByPath("tasks." + taskID)
		ctx.SetFunctionContext(fc)
	}
	// We don't scan wheel slots; unknown IDs will be ignored on tick.
}

func cancelAll(ctx *sfPlugins.StatefunContextProcessor) {
	fc := ctx.GetFunctionContext()
	fc.SetByPath("tasks", easyjson.NewJSONObject())
	wheelSize := int(fc.GetByPath("config.wheel_size").AsNumericDefault(3600))
	arr := easyjson.NewJSONArray()
	for i := 0; i < wheelSize; i++ {
		obj := easyjson.NewJSONObject()
		obj.SetByPath("ids", easyjson.NewJSONArray())
		arr.AddToArray(obj)
	}
	fc.SetByPath("wheel", arr)
	ctx.SetFunctionContext(fc)
}

// ---------- Tick processing ----------
func processTick(ctx *sfPlugins.StatefunContextProcessor) {
	fc := ctx.GetFunctionContext()
	wheelSize := int(fc.GetByPath("config.wheel_size").AsNumericDefault(3600))
	currentSlot := int(fc.GetByPath("current_slot").AsNumericDefault(0))

	// Drain current slot
	slotPath := fmt.Sprintf("wheel.%d.ids", currentSlot)
	idsArr := fc.GetByPath(slotPath)
	if !idsArr.IsArray() {
		idsArr = easyjson.NewJSONArray()
	}

	newSlotIds := easyjson.NewJSONArray()

	for i := 0; i < idsArr.ArraySize(); i++ {
		taskID := idsArr.ArrayElement(i).AsStringDefault("")
		if taskID == "" {
			continue
		}
		if !fc.PathExists("tasks." + taskID) {
			continue
		}

		entry := fc.GetByPath("tasks." + taskID)
		rounds := int(entry.GetByPath("rounds").AsNumericDefault(0))
		if rounds > 0 {
			entry.SetByPath("rounds", easyjson.NewJSON(rounds-1))
			fc.SetByPath("tasks."+taskID, entry)
			newSlotIds.AddToArray(easyjson.NewJSON(taskID))
			continue
		}

		// Fire now
		callerTypename := entry.GetByPath("caller_typename").AsStringDefault(ctx.Self.Typename)
		callerID := entry.GetByPath("caller_id").AsStringDefault(ctx.Self.ID)
		targetTypename := entry.GetByPath("target_typename").AsStringDefault("")
		targetID := entry.GetByPath("target_id").AsStringDefault("")
		var payload *easyjson.JSON
		if entry.PathExists("payload") {
			p := entry.GetByPath("payload")
			payload = &p
		}
		var options *easyjson.JSON
		if entry.PathExists("options") {
			o := entry.GetByPath("options")
			options = &o
		}
		if BaseSignalFunc == nil {
			_ = ctx.Signal(sfPlugins.JetstreamGlobalSignal, targetTypename, targetID, payload, options)
		} else {
			BaseSignalFunc(sfPlugins.JetstreamGlobalSignal, callerTypename, callerID, targetTypename, targetID, payload, options)
		}

		// Reschedule if periodic
		if entry.GetByPath("kind").AsStringDefault("") == "every" {
			periodTicks := int(entry.GetByPath("period_ticks").AsNumericDefault(1))
			if periodTicks < 1 {
				periodTicks = 1
			}
			nextSlot := (currentSlot + (periodTicks % wheelSize)) % wheelSize
			nextRounds := periodTicks / wheelSize
			entry.SetByPath("rounds", easyjson.NewJSON(nextRounds))
			fc.SetByPath("tasks."+taskID, entry)

			nextPath := fmt.Sprintf("wheel.%d.ids", nextSlot)
			nextIds := fc.GetByPath(nextPath)
			if !nextIds.IsArray() {
				nextIds = easyjson.NewJSONArray()
			}
			nextIds.AddToArray(easyjson.NewJSON(taskID))
			fc.SetByPath(nextPath, nextIds)
		} else {
			// one-shot
			fc.RemoveByPath("tasks." + taskID)
		}
	}

	// Replace current slot ids with survivors
	fc.SetByPath(slotPath, newSlotIds)

	// Advance slot
	nextSlot := (currentSlot + 1) % wheelSize
	fc.SetByPath("current_slot", easyjson.NewJSON(nextSlot))
	ctx.SetFunctionContext(fc)

	// Keep ticking while tasks exist: block until next tick, self-signal, then return
	if len(fc.GetByPath("tasks").ObjectKeys()) > 0 {
		scheduleNextTick(ctx)
	} else {
		fc.SetByPath("ticker_active", easyjson.NewJSON(false))
		ctx.SetFunctionContext(fc)
	}
}
